config:
  send_anonymous_usage_stats: False
  use_colors: True
  partial_parse: True

jaffle_shop:
  outputs:
    dev:
      type: postgres
      threads: 1
      host: rc1d-o4pej0lsvgkw06wt.mdb.yandexcloud.net
      port: 6432
      user: kzhukov
      pass: dbt_kzhukov
      dbname: db1
      schema: public
  target: dev  